### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by SirFlayte** [Androz2091/dotapps#1]
Hey ! C'est sympa de créer un dépôt GH pour répertorier les applications que tu utilises.

Cependant, je trouve que c'est assez inutile d'en faire un dépôt GH pour cela, selon moi ce serait peut-être mieux d'en faire un article sur ton blog, puis de le link sur le read-me de ton profil avec un truc qui ressemble à :

> My apps : *lien vers l'article*

C'est pas grand chose mais je trouve que ce serait plus pratique, de plus, étant donné que tu as un joli nombre de projets open-source, le dépôt risque de ne pas être vu.

**Comment by Androz2091** [comment]
Salut, c'est a la base plus un dépôt pour moi que pour les autres, je m'en sers pour avoir une liste claire de toutes les applis que je dois réinstaller après mes fréquentes RAZ

**Comment by Androz2091** [comment]
Maintenir une liste dans un vrai article prendrait trop de temps. Par contre si vous avez des suggestions ça reste un dépôt normal, hésitez pas à pr
